"""Product Catalog — 20 Vouge Studio SKUs for PriceEngine."""


DEFAULT_PRODUCTS = {
    # ═══════════════════════════════════════════════
    # T-SHIRTS (5 products)
    # ═══════════════════════════════════════════════
    "vs-essential-cotton-tee": {
        "id": "vs-essential-cotton-tee",
        "name": "Essential Cotton Crew-Neck Tee",
        "brand": "Vouge Studio",
        "price": 799,
        "cost_price": 280,
        "currency": "INR",
        "category": "T-Shirts",
        "sku": "VS-TEE-001",
        "search_query": "white cotton crew neck t-shirt men",
        "description": "Everyday crew-neck tee in premium combed cotton. Relaxed fit, pre-shrunk fabric, perfect for layering or wearing solo.",
        "specifications": {
            "fit": "Relaxed fit",
            "material": "100% Combed Cotton",
            "color": "White",
            "neckline": "Crew-neck",
            "sleeve": "Short sleeve",
            "weight": "180 GSM",
        },
        "sizes": ["XS", "S", "M", "L", "XL", "XXL"],
        "stock": 1200,
        "rating": 4.5,
        "reviews": 342,
    },
    "vs-polo-classic": {
        "id": "vs-polo-classic",
        "name": "Classic Piqué Polo",
        "brand": "Vouge Studio",
        "price": 1299,
        "cost_price": 450,
        "currency": "INR",
        "category": "T-Shirts",
        "sku": "VS-TEE-002",
        "search_query": "men classic polo t-shirt pique cotton",
        "description": "Timeless polo in textured piqué cotton with ribbed collar and two-button placket. Smart-casual essential.",
        "specifications": {
            "fit": "Regular fit",
            "material": "100% Piqué Cotton",
            "color": "Navy Blue",
            "neckline": "Polo collar",
            "sleeve": "Short sleeve",
            "weight": "220 GSM",
        },
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "stock": 800,
        "rating": 4.4,
        "reviews": 218,
    },
    "vs-oversized-graphic": {
        "id": "vs-oversized-graphic",
        "name": "Oversized Graphic Print Tee",
        "brand": "Vouge Studio",
        "price": 999,
        "cost_price": 340,
        "currency": "INR",
        "category": "T-Shirts",
        "sku": "VS-TEE-003",
        "search_query": "oversized graphic print t-shirt men streetwear",
        "description": "Drop-shoulder oversized tee with bold chest graphic. Heavy-weight cotton for that premium streetwear drape.",
        "specifications": {
            "fit": "Oversized",
            "material": "100% Cotton",
            "color": "Black",
            "neckline": "Round neck",
            "sleeve": "Drop shoulder",
            "weight": "240 GSM",
        },
        "sizes": ["S", "M", "L", "XL"],
        "stock": 650,
        "rating": 4.6,
        "reviews": 189,
    },
    "vs-henley-waffle": {
        "id": "vs-henley-waffle",
        "name": "Waffle-Knit Henley",
        "brand": "Vouge Studio",
        "price": 1199,
        "cost_price": 420,
        "currency": "INR",
        "category": "T-Shirts",
        "sku": "VS-TEE-004",
        "search_query": "men waffle knit henley t-shirt full sleeve",
        "description": "Textured waffle-knit henley with three-button placket and roll-up sleeves. Ideal transitional layering piece.",
        "specifications": {
            "fit": "Slim fit",
            "material": "Cotton Waffle Knit",
            "color": "Olive Green",
            "neckline": "Henley",
            "sleeve": "Full sleeve",
            "weight": "200 GSM",
        },
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "stock": 520,
        "rating": 4.3,
        "reviews": 147,
    },
    "vs-stripe-tee": {
        "id": "vs-stripe-tee",
        "name": "Breton Stripe Tee",
        "brand": "Vouge Studio",
        "price": 899,
        "cost_price": 310,
        "currency": "INR",
        "category": "T-Shirts",
        "sku": "VS-TEE-005",
        "search_query": "men breton stripe t-shirt navy white",
        "description": "French-inspired horizontal stripe tee in soft jersey cotton. A wardrobe staple that pairs with everything.",
        "specifications": {
            "fit": "Regular fit",
            "material": "100% Cotton Jersey",
            "color": "Navy/White Stripe",
            "neckline": "Boat neck",
            "sleeve": "Short sleeve",
            "weight": "180 GSM",
        },
        "sizes": ["S", "M", "L", "XL"],
        "stock": 700,
        "rating": 4.2,
        "reviews": 124,
    },

    # ═══════════════════════════════════════════════
    # JEANS (5 products)
    # ═══════════════════════════════════════════════
    "vs-slim-indigo": {
        "id": "vs-slim-indigo",
        "name": "Slim-Fit Indigo Wash Jeans",
        "brand": "Vouge Studio",
        "price": 2499,
        "cost_price": 900,
        "currency": "INR",
        "category": "Jeans",
        "sku": "VS-JNS-001",
        "search_query": "men slim fit indigo jeans stretch denim",
        "description": "Classic slim-fit jeans in deep indigo wash with 2% stretch for all-day comfort. Five-pocket styling.",
        "specifications": {
            "fit": "Slim fit",
            "material": "98% Cotton, 2% Elastane",
            "color": "Indigo",
            "rise": "Mid rise",
            "wash": "Dark indigo",
            "weight": "12 oz denim",
        },
        "sizes": ["28", "30", "32", "34", "36", "38"],
        "stock": 900,
        "rating": 4.5,
        "reviews": 312,
    },
    "vs-relaxed-black": {
        "id": "vs-relaxed-black",
        "name": "Relaxed-Fit Black Jeans",
        "brand": "Vouge Studio",
        "price": 2299,
        "cost_price": 820,
        "currency": "INR",
        "category": "Jeans",
        "sku": "VS-JNS-002",
        "search_query": "men relaxed fit black jeans straight leg",
        "description": "Easy-wearing relaxed jeans in jet black with a straight leg. Garment-dyed for a soft hand feel.",
        "specifications": {
            "fit": "Relaxed fit",
            "material": "100% Cotton Denim",
            "color": "Black",
            "rise": "Mid rise",
            "wash": "Garment dyed",
            "weight": "11.5 oz denim",
        },
        "sizes": ["28", "30", "32", "34", "36"],
        "stock": 680,
        "rating": 4.3,
        "reviews": 198,
    },
    "vs-skinny-grey": {
        "id": "vs-skinny-grey",
        "name": "Skinny-Fit Grey Jeans",
        "brand": "Vouge Studio",
        "price": 2699,
        "cost_price": 950,
        "currency": "INR",
        "category": "Jeans",
        "sku": "VS-JNS-003",
        "search_query": "men skinny fit grey jeans stretch",
        "description": "Figure-hugging skinny jeans in smoky grey with power stretch. Tapered leg with a clean finish.",
        "specifications": {
            "fit": "Skinny fit",
            "material": "95% Cotton, 3% Polyester, 2% Elastane",
            "color": "Smoke Grey",
            "rise": "Low rise",
            "wash": "Light grey",
            "weight": "10.5 oz denim",
        },
        "sizes": ["28", "30", "32", "34", "36"],
        "stock": 450,
        "rating": 4.1,
        "reviews": 156,
    },
    "vs-cargo-khaki": {
        "id": "vs-cargo-khaki",
        "name": "Cargo Utility Jeans",
        "brand": "Vouge Studio",
        "price": 2799,
        "cost_price": 1000,
        "currency": "INR",
        "category": "Jeans",
        "sku": "VS-JNS-004",
        "search_query": "men cargo jeans utility pockets khaki",
        "description": "Modern cargo jeans with flap utility pockets and adjustable ankle snaps. Military-inspired street style.",
        "specifications": {
            "fit": "Loose fit",
            "material": "100% Cotton Twill",
            "color": "Khaki",
            "rise": "Mid rise",
            "wash": "Enzyme washed",
            "weight": "11 oz twill",
        },
        "sizes": ["30", "32", "34", "36", "38"],
        "stock": 380,
        "rating": 4.4,
        "reviews": 203,
    },
    "vs-wide-leg-blue": {
        "id": "vs-wide-leg-blue",
        "name": "Wide-Leg Vintage Wash Jeans",
        "brand": "Vouge Studio",
        "price": 2599,
        "cost_price": 930,
        "currency": "INR",
        "category": "Jeans",
        "sku": "VS-JNS-005",
        "search_query": "men wide leg vintage wash jeans baggy",
        "description": "90s-inspired wide-leg jeans in vintage mid-blue wash. Relaxed through hip and thigh with a dramatic flare.",
        "specifications": {
            "fit": "Wide leg",
            "material": "100% Cotton Denim",
            "color": "Vintage Blue",
            "rise": "High rise",
            "wash": "Vintage mid-blue",
            "weight": "13 oz denim",
        },
        "sizes": ["28", "30", "32", "34", "36"],
        "stock": 320,
        "rating": 4.2,
        "reviews": 134,
    },

    # ═══════════════════════════════════════════════
    # DRESSES (5 products)
    # ═══════════════════════════════════════════════
    "vs-midi-floral": {
        "id": "vs-midi-floral",
        "name": "Floral Print Midi Dress",
        "brand": "Vouge Studio",
        "price": 2999,
        "cost_price": 1050,
        "currency": "INR",
        "category": "Dresses",
        "sku": "VS-DRS-001",
        "search_query": "women floral print midi dress summer",
        "description": "Flowing midi dress in vibrant floral print with smocked waist and puff sleeves. Perfect for brunch to date night.",
        "specifications": {
            "fit": "A-line",
            "material": "Viscose Rayon",
            "color": "Pink Floral",
            "length": "Midi (below knee)",
            "sleeve": "Puff sleeve",
            "closure": "Back zip",
        },
        "sizes": ["XS", "S", "M", "L", "XL"],
        "stock": 400,
        "rating": 4.6,
        "reviews": 267,
    },
    "vs-bodycon-ribbed": {
        "id": "vs-bodycon-ribbed",
        "name": "Ribbed Bodycon Dress",
        "brand": "Vouge Studio",
        "price": 1799,
        "cost_price": 620,
        "currency": "INR",
        "category": "Dresses",
        "sku": "VS-DRS-002",
        "search_query": "women ribbed bodycon dress sleeveless",
        "description": "Form-fitting ribbed knit dress with square neckline and adjustable spaghetti straps. Day-to-night versatility.",
        "specifications": {
            "fit": "Bodycon",
            "material": "95% Cotton, 5% Spandex",
            "color": "Charcoal",
            "length": "Mini (above knee)",
            "sleeve": "Sleeveless",
            "closure": "Pull-on",
        },
        "sizes": ["XS", "S", "M", "L"],
        "stock": 550,
        "rating": 4.3,
        "reviews": 178,
    },
    "vs-shirt-dress": {
        "id": "vs-shirt-dress",
        "name": "Oversized Shirt Dress",
        "brand": "Vouge Studio",
        "price": 2499,
        "cost_price": 880,
        "currency": "INR",
        "category": "Dresses",
        "sku": "VS-DRS-003",
        "search_query": "women oversized shirt dress cotton button down",
        "description": "Crisp cotton shirt dress with an oversized silhouette, chest pocket, and self-tie belt. Office to weekend ease.",
        "specifications": {
            "fit": "Oversized",
            "material": "100% Cotton Poplin",
            "color": "Sky Blue",
            "length": "Knee length",
            "sleeve": "Full sleeve (roll-up tab)",
            "closure": "Button front",
        },
        "sizes": ["S", "M", "L", "XL"],
        "stock": 360,
        "rating": 4.5,
        "reviews": 143,
    },
    "vs-maxi-satin": {
        "id": "vs-maxi-satin",
        "name": "Satin Slip Maxi Dress",
        "brand": "Vouge Studio",
        "price": 3499,
        "cost_price": 1250,
        "currency": "INR",
        "category": "Dresses",
        "sku": "VS-DRS-004",
        "search_query": "women satin slip maxi dress evening",
        "description": "Luxe satin maxi with cowl neckline and cross-back straps. The ultimate evening statement in liquid fabric.",
        "specifications": {
            "fit": "Bias cut",
            "material": "Satin (Polyester)",
            "color": "Emerald Green",
            "length": "Maxi (floor length)",
            "sleeve": "Spaghetti straps",
            "closure": "Invisible side zip",
        },
        "sizes": ["XS", "S", "M", "L"],
        "stock": 250,
        "rating": 4.7,
        "reviews": 302,
    },
    "vs-wrap-dress": {
        "id": "vs-wrap-dress",
        "name": "Classic Wrap Dress",
        "brand": "Vouge Studio",
        "price": 2799,
        "cost_price": 980,
        "currency": "INR",
        "category": "Dresses",
        "sku": "VS-DRS-005",
        "search_query": "women wrap dress jersey knee length",
        "description": "Universally flattering wrap dress in matte jersey with a true wrap closure and flared skirt.",
        "specifications": {
            "fit": "Wrap / Fitted waist",
            "material": "95% Polyester, 5% Elastane Jersey",
            "color": "Burgundy",
            "length": "Knee length",
            "sleeve": "3/4 sleeve",
            "closure": "Wrap tie",
        },
        "sizes": ["XS", "S", "M", "L", "XL"],
        "stock": 420,
        "rating": 4.4,
        "reviews": 231,
    },

    # ═══════════════════════════════════════════════
    # JACKETS (5 products)
    # ═══════════════════════════════════════════════
    "vs-bomber-jacket": {
        "id": "vs-bomber-jacket",
        "name": "Nylon Bomber Jacket",
        "brand": "Vouge Studio",
        "price": 3999,
        "cost_price": 1400,
        "currency": "INR",
        "category": "Jackets",
        "sku": "VS-JKT-001",
        "search_query": "men nylon bomber jacket zip up",
        "description": "Lightweight nylon bomber with ribbed cuffs, zip pockets, and satin lining. The go-to transitional jacket.",
        "specifications": {
            "fit": "Regular fit",
            "material": "Nylon shell, Polyester lining",
            "color": "Army Green",
            "closure": "Front zip",
            "pockets": "2 zip + 1 internal",
            "weight": "Lightweight",
        },
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "stock": 300,
        "rating": 4.5,
        "reviews": 256,
    },
    "vs-denim-jacket": {
        "id": "vs-denim-jacket",
        "name": "Classic Denim Trucker Jacket",
        "brand": "Vouge Studio",
        "price": 3499,
        "cost_price": 1250,
        "currency": "INR",
        "category": "Jackets",
        "sku": "VS-JKT-002",
        "search_query": "men denim trucker jacket blue classic",
        "description": "Iconic trucker silhouette in rigid 12 oz denim with chest flap pockets and adjustable waist tabs.",
        "specifications": {
            "fit": "Regular fit",
            "material": "100% Cotton Denim (12 oz)",
            "color": "Medium Blue",
            "closure": "Button front",
            "pockets": "4 (2 chest flap, 2 side)",
            "weight": "Medium weight",
        },
        "sizes": ["S", "M", "L", "XL"],
        "stock": 280,
        "rating": 4.6,
        "reviews": 189,
    },
    "vs-windbreaker": {
        "id": "vs-windbreaker",
        "name": "Packable Windbreaker",
        "brand": "Vouge Studio",
        "price": 2999,
        "cost_price": 1050,
        "currency": "INR",
        "category": "Jackets",
        "sku": "VS-JKT-003",
        "search_query": "men packable windbreaker jacket lightweight",
        "description": "Ultralight hooded windbreaker that packs into its own pocket. Water-resistant coating for sudden showers.",
        "specifications": {
            "fit": "Slim fit",
            "material": "Ripstop Nylon",
            "color": "Black",
            "closure": "Half zip",
            "pockets": "1 kangaroo + 1 back",
            "weight": "Ultra-lightweight (120g)",
        },
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "stock": 420,
        "rating": 4.3,
        "reviews": 167,
    },
    "vs-blazer-knit": {
        "id": "vs-blazer-knit",
        "name": "Knit Blazer",
        "brand": "Vouge Studio",
        "price": 4999,
        "cost_price": 1800,
        "currency": "INR",
        "category": "Jackets",
        "sku": "VS-JKT-004",
        "search_query": "men knit blazer casual smart unstructured",
        "description": "Unstructured knit blazer combining tailoring with comfort. Patch pockets and natural shoulder for a relaxed elegance.",
        "specifications": {
            "fit": "Slim fit",
            "material": "Cotton-Polyester Blend Knit",
            "color": "Charcoal Melange",
            "closure": "Two-button",
            "pockets": "3 (2 patch, 1 breast)",
            "weight": "Medium weight",
        },
        "sizes": ["S", "M", "L", "XL"],
        "stock": 200,
        "rating": 4.4,
        "reviews": 98,
    },
    "vs-trench-coat": {
        "id": "vs-trench-coat",
        "name": "Double-Breasted Trench Coat",
        "brand": "Vouge Studio",
        "price": 5999,
        "cost_price": 2100,
        "currency": "INR",
        "category": "Jackets",
        "sku": "VS-JKT-005",
        "search_query": "men double breasted trench coat classic",
        "description": "Heritage-inspired trench coat with storm flap, belt, and check lining. A timeless outerwear investment piece.",
        "specifications": {
            "fit": "Regular fit",
            "material": "Cotton Gabardine, Check Polyester Lining",
            "color": "Khaki / Stone",
            "closure": "Double-breasted button",
            "pockets": "2 side + 1 internal",
            "weight": "Heavy weight",
        },
        "sizes": ["S", "M", "L", "XL"],
        "stock": 150,
        "rating": 4.7,
        "reviews": 142,
    },
}


def get_all_products() -> list[dict]:
    """Return all 20 Vouge Studio products as a list of dicts."""
    return list(DEFAULT_PRODUCTS.values())


def get_product_by_id(product_id: str) -> dict | None:
    """Return a single product dict by ID, or None if not found."""
    return DEFAULT_PRODUCTS.get(product_id)


# Alias used by dashboard/analytics routes
get_product = get_product_by_id


def get_products_by_category(category: str) -> list[dict]:
    """Return all products matching a given category (case-insensitive)."""
    cat = category.strip().lower()
    return [p for p in DEFAULT_PRODUCTS.values() if p["category"].lower() == cat]
