import React, { useState, useEffect } from 'react';
import { AlertCircle, TrendingUp, Zap, Lightbulb, Loader } from 'lucide-react';
import API from '../api/client';
import './AIInsightCards.css';

/**
 * AIInsightCards Component
 * 
 * Displays 4 key AI-generated insights for a product:
 * - Market Risk (red/warning)
 * - Revenue Opportunity (green)
 * - Trend Alert (orange)
 * - AI Recommendation (blue)
 */

const INSIGHT_CONFIG = {
  market_risk: {
    icon: AlertCircle,
    color: '#EF4444',
    bgColor: '#EF444408',
    borderColor: '#EF4444',
  },
  revenue_opportunity: {
    icon: TrendingUp,
    color: '#22C55E',
    bgColor: '#22C55E08',
    borderColor: '#22C55E',
  },
  trend_alert: {
    icon: Zap,
    color: '#F59E0B',
    bgColor: '#F59E0B08',
    borderColor: '#F59E0B',
  },
  ai_recommendation: {
    icon: Lightbulb,
    color: '#3B82F6',
    bgColor: '#3B82F608',
    borderColor: '#3B82F6',
  },
};

export default function AIInsightCards({ productId, isCompact = false }) {
  const [insights, setInsights] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    if (!productId) return;
    
    fetchInsights();
  }, [productId]);

  const fetchInsights = async () => {
    setIsLoading(true);
    setError(null);
    try {
      const response = await API.get(`/api/copilot/insights/${productId}`);
      setInsights(response.data.cards || []);
    } catch (err) {
      console.error('Failed to fetch insights:', err);
      setError('Could not load AI insights');
    } finally {
      setIsLoading(false);
    }
  };

  if (isLoading) {
    return (
      <div className={`insight-cards-container ${isCompact ? 'compact' : ''}`}>
        <div className="insight-cards-loading">
          <Loader size={24} className="spinner" />
          <p>Analyzing market opportunities...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className={`insight-cards-container ${isCompact ? 'compact' : ''}`}>
        <div className="insight-cards-error">
          <p>{error}</p>
          <button onClick={fetchInsights} className="retry-btn">
            Try Again
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className={`insight-cards-container ${isCompact ? 'compact' : ''}`}>
      {isCompact && (
        <div className="insight-cards-header">
          <h3>📊 AI Insights</h3>
          <button onClick={fetchInsights} className="refresh-btn" title="Refresh insights">
            ↻
          </button>
        </div>
      )}

      <div className="insight-cards-grid">
        {insights.map((insight, idx) => {
          const config = INSIGHT_CONFIG[insight.type] || INSIGHT_CONFIG.ai_recommendation;
          const Icon = config.icon;

          return (
            <div
              key={idx}
              className="insight-card"
              style={{
                background: config.bgColor,
                borderColor: config.borderColor,
                borderWidth: '1.5px',
              }}
            >
              <div className="insight-card-icon" style={{ color: config.color }}>
                <Icon size={20} />
              </div>

              <div className="insight-card-content">
                <h4 style={{ color: config.color }}>
                  {insight.title}
                </h4>
                <p>{insight.description}</p>

                {insight.impact_pct && (
                  <div className="insight-impact">
                    <span style={{ color: config.color }}>
                      {insight.impact_pct > 0 ? '+' : ''}{insight.impact_pct.toFixed(1)}%
                    </span>
                    {insight.type === 'market_risk' && 'impact'}
                    {insight.type === 'revenue_opportunity' && 'potential'}
                    {insight.type === 'trend_alert' && 'sensitivity'}
                    {insight.type === 'ai_recommendation' && 'expected'}
                  </div>
                )}
              </div>

              {insight.severity && (
                <div className="insight-severity" style={{ color: config.color }}>
                  {insight.severity}
                </div>
              )}
            </div>
          );
        })}
      </div>

      {!isCompact && (
        <div className="insight-cards-footer">
          <p>💡 These insights are generated by AI analysis of market data, competitor activity, and demand patterns.</p>
        </div>
      )}
    </div>
  );
}
